sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

branches:
  only:
    - master

install:
  - pip install coveralls

script:
  - coverage run -m unittest discover -s test

after_success:
  - coveralls
  
